server:
  port: 7071
spring:
  application:
    name: spring-cloud-consumer-application
  cloud:
    zookeeper:
      connect-string: localhost:2181
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848